#!/usr/bin/env python3
"""Generate inspectable runtime constants for the ME-LVQA filler."""

from __future__ import annotations

import argparse
import json
from datetime import datetime, timezone
from pathlib import Path


def _ordinal_word(n: int) -> str:
    if not (1 <= n <= 99):
        raise ValueError(f"ordinal out of supported range: {n}")

    base_ord = {
        1: "first",
        2: "second",
        3: "third",
        4: "fourth",
        5: "fifth",
        6: "sixth",
        7: "seventh",
        8: "eighth",
        9: "ninth",
        10: "tenth",
        11: "eleventh",
        12: "twelfth",
        13: "thirteenth",
        14: "fourteenth",
        15: "fifteenth",
        16: "sixteenth",
        17: "seventeenth",
        18: "eighteenth",
        19: "nineteenth",
    }
    tens_card = {20: "twenty", 30: "thirty", 40: "forty", 50: "fifty", 60: "sixty", 70: "seventy", 80: "eighty", 90: "ninety"}
    tens_ord = {20: "twentieth", 30: "thirtieth", 40: "fortieth", 50: "fiftieth", 60: "sixtieth", 70: "seventieth", 80: "eightieth", 90: "ninetieth"}

    if n < 20:
        return base_ord[n]
    tens = (n // 10) * 10
    unit = n % 10
    if unit == 0:
        return tens_ord[tens]
    return f"{tens_card[tens]}-{base_ord[unit]}"


def _build_ordinal_map(max_ordinal: int) -> dict[str, int]:
    return {_ordinal_word(i): i for i in range(1, max_ordinal + 1)}


def _build_config(max_ordinal: int) -> dict:
    dataset_rules = {
        "casme3": {
            "video_regex": r"^[a-z0-9]+_[a-z]\d+$",
            "regex_flags": ["IGNORECASE"],
            "video_prefixes": ["spno."],
            "provenance": "rule-based identifier format used in dataset detection",
        },
        "samm": {
            "video_regex": r"^\d+_\d+_\d+$",
            "regex_flags": [],
            "video_prefixes": [],
            "provenance": "rule-based identifier format used in dataset detection",
        },
    }

    return {
        "meta": {
            "generator": "util/generate_lvqa_constants_json.py",
            "generated_utc": datetime.now(timezone.utc).isoformat(),
            "notes": [
                "Ordinal words are programmatically generated from English ordinal rules.",
                "Dataset regex rules are declared as detection rules and consumed at runtime.",
            ],
        },
        "labels": {
            "micro_expression": "micro-expression",
            "macro_expression": "macro-expression",
            "provenance": "task ontology labels",
        },
        "datasets": list(dataset_rules.keys()),
        "dataset_detection": {
            "rules": dataset_rules,
            "fallback_dataset": "unknown",
        },
        "ordinal_word_to_int": {
            "max_ordinal": max_ordinal,
            "mapping": _build_ordinal_map(max_ordinal),
            "provenance": "generated by ordinal rule function",
        },
    }


def main() -> None:
    parser = argparse.ArgumentParser(description="Generate me_lvqa_util/config_constants.json")
    parser.add_argument(
        "--output",
        default=str(Path(__file__).resolve().parent.parent / "me_lvqa_util" / "config_constants.json"),
        help="Output JSON path.",
    )
    parser.add_argument("--max-ordinal", type=int, default=35, help="Largest ordinal index to generate.")
    args = parser.parse_args()

    cfg = _build_config(max_ordinal=args.max_ordinal)
    out_path = Path(args.output).resolve()
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(json.dumps(cfg, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")
    print(f"Wrote {out_path}")


if __name__ == "__main__":
    main()
